# Generated by Django 5.2.4 on 2025-07-04 06:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Food Name')),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Calories (per 100g)')),
                ('protien', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Protien (per 100g)')),
                ('carps', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Carps (per 100g)')),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Fat (per 100g)')),
                ('unit', models.CharField(default='g', max_length=50, verbose_name='Unit of Measurement')),
                ('external_api_id', models.CharField(blank=True, help_text='ID from external food database (e.g., Open Food Facts)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this custom food item (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_food_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255, verbose_name='Food Name')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantity Consumed')),
                ('quantity_unit', models.CharField(max_length=50, verbose_name='Quantity Unit')),
                ('calories_consumed', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Calories Consumed')),
                ('protein_consumed', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Protein Consumed')),
                ('carbs_consumed', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Carbohydrates Consumed')),
                ('fat_consumed', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Fat Consumed')),
                ('log_date', models.DateField(default=django.utils.timezone.now, verbose_name='Log Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_entries', to='foodtracker.fooditem', verbose_name='Food Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Food Log Entry',
                'verbose_name_plural': 'Food Log Entries',
                'ordering': ['-log_date', '-created_at'],
            },
        ),
    ]
