# Generated by Django 5.2.4 on 2025-07-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Fiber (per 100g)'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sugars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sugars (per 100g)'),
        ),
        migrations.AddField(
            model_name='foodlogentry',
            name='fiber_consumed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Fiber Consumed'),
        ),
        migrations.AddField(
            model_name='foodlogentry',
            name='sugars_consumed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Sugars Consumed'),
        ),
    ]
