# Generated by Django 5.2.4 on 2025-07-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0002_fooditem_fiber_fooditem_sugars_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='protien',
            new_name='protein',
        ),
    ]
