# Generated by Django 5.2.4 on 2025-07-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0003_rename_protien_fooditem_protein'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='carps',
            new_name='carbs',
        ),
    ]
